version: '3.8'

services:
  paperless-ai:
    build: .
    container_name: paperless-ai
    volumes:
      - data:/app/data
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  data: