name: "🐞 Bug Report"
description: "Report a bug or unexpected behavior"
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - ""

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please provide all necessary details to help us investigate and fix the issue.

  - type: input
    id: bug_summary
    attributes:
      label: "🔍 Describe the Bug"
      description: "A clear and concise summary of the issue."
      placeholder: "Bug description..."
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "📖 Detailed Description"
      description: "Explain what the issue is in detail."
      placeholder: "Provide more context about the bug, including any observations."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "Expected result..."
    validations:
      required: true

  - type: textarea
    id: docker_logs
    attributes:
      label: "📜 Docker Container Logs"
      description: "Provide relevant logs from the Docker container. If possible, include only the error message."
      placeholder: "Paste logs or error messages here..."
      
  - type: textarea
    id: screenshots
    attributes:
      label: "🖼️ Screenshots"
      description: "Attach screenshots if applicable."
      placeholder: "Drag & drop images or provide a link."

  - type: dropdown
    id: operating_system
    attributes:
      label: "🖥️ Desktop Environment"
      description: "Select the OS where the issue occurs."
      multiple: false
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other"
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: "💻 OS Version"
      description: "Enter the version of your operating system."
      placeholder: "e.g. Windows 11, macOS 14, Ubuntu 22.04"

  - type: input
    id: browser
    attributes:
      label: "🌐 Browser"
      description: "Which browser are you using (if applicable)?"
      placeholder: "e.g. Chrome, Safari, Firefox"

  - type: input
    id: browser_version
    attributes:
      label: "🔢 Browser Version"
      description: "Enter the version of your browser (if applicable)."
      placeholder: "e.g. 120.0.6099.199"

  - type: dropdown
    id: smartphone_device
    attributes:
      label: "📱 Smartphone (if applicable)"
      description: "Select the affected mobile device."
      multiple: false
      options:
        - "Not applicable"
        - "iPhone"
        - "iPad"
        - "Samsung"
        - "Pixel"
        - "Other"

  - type: input
    id: smartphone_os
    attributes:
      label: "📱 Mobile OS Version"
      description: "Specify the OS version of your smartphone (if applicable)."
      placeholder: "e.g. iOS 17.1, Android 14"

  - type: input
    id: smartphone_browser
    attributes:
      label: "🌐 Mobile Browser"
      description: "Specify the browser you used on mobile (if applicable)."
      placeholder: "e.g. Safari, Chrome, Firefox"

  - type: checkboxes
    id: additional_info
    attributes:
      label: "📝 Additional Information"
      description: "Select any that apply."
      options:
        - label: "I have checked existing issues and this is not a duplicate"
          required: true
        - label: "I have tried debugging this issue on my own"
        - label: "I can provide a fix and submit a PR"

  - type: textarea
    id: extra_notes
    attributes:
      label: "📌 Extra Notes"
      description: "Anything else you'd like to add?"
      placeholder: "Additional comments or findings..."
